"""Initial migration

Revision ID: d97c585f36bd
Revises: 
Create Date: 2025-06-20 09:16:25.396462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97c585f36bd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('guest_type_id', sa.Integer(), nullable=False))
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.create_foreign_key(None, 'guest_type', ['guest_type_id'], ['id'])
        batch_op.drop_column('checked_in')
        batch_op.drop_column('table_number')
        batch_op.drop_column('num_guests')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest', schema=None) as batch_op:
        batch_op.add_column(sa.Column('num_guests', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('table_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('checked_in', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('guest_type_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
